# Generated by Django 5.0 on 2024-08-09 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_question_subject_alter_subject_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='description',
            field=models.CharField(default='No description', max_length=256),
        ),
        migrations.AddField(
            model_name='subject',
            name='icon',
            field=models.CharField(default='No icon', max_length=256),
        ),
    ]
